### ISSUE TITLE
The (g) letters in profile menu are cut off

### ISSUE THREAD

**Issue by Void48** [williamckha/spicetify-fluent#11]
![image](https://user-images.githubusercontent.com/85196642/135766130-2633dd3a-073d-459a-81ff-cd1ddc02f573.png)

**Comment by williamckha** [comment]
I'm unable to reproduce this issue, are you using the latest version of the theme?

**Comment by aayushyap89** [comment]
How are you enable to reproduce it. I just installed fluent theme again and the g's are cut out from the bottom just like his.

**Comment by Anthony2be** [comment]
> I'm unable to reproduce this issue, are you using the latest version of the theme?

i installed it and it has the same issue

**Comment by sagars007** [comment]
Yeah this issue is still there in the latest version. Looks like it's a text-overflow problem and it's there in many places in the theme. [For example here.](https://imgur.com/a/kMK4sPc) To fix this, comment out or remove the overflow code in line 204 of user.css

```
h1,
h2,
h3,
.main-shelf-title,
.main-entityHeader-topbarTitle,
.main-type-canon,
.main-type-bass,
.main-cardHeader-text.main-type-alto,
.x-searchResultsTracks-title {
  font-family: 'Segoe UI', sans-serif !important;
  font-weight: 500;
  letter-spacing: 0.1px !important;
  /*overflow: visible !important;*/  /*this is line 204 in user.css*/
  margin-bottom: 4px;
  white-space: normal;
}
```
You can change the overflow property of other elements also by targeting them using devTools and doing the same. Hopefully this should hold you over until the theme author gets around to fixing it officially. The random css class names keep changing every Spotify update and this breaks some of the css rules.

**Comment by sagars007** [comment]
> ![image](https://user-images.githubusercontent.com/85196642/135766130-2633dd3a-073d-459a-81ff-cd1ddc02f573.png)

This is a problem with the Segoe UI font used in the theme. When the default Spotify font is used there are no issues with any text. I tried changing the overflow property of it, but it adversely affects text overflow in other places. You can remove all mentions of the font-family code in user.css for now as a temporary fix (if you are ok with not using Segoe UI font).

[Here's how it looks](https://imgur.com/a/I3tpJJE)
