### ISSUE TITLE
Double listing in Marketplace

### ISSUE THREAD

**Issue by theRealPadster** [williamckha/spicetify-fluent#55]
Hey I just noticed that your theme is listed twice in Spicetify Marketplace. I thought it was a bug, but it looks like it's because it's listed in the manifest here as well as in the community themes repo. Would it be alright with you if we removed it from the community themes manifest? It would still be included in the community themes github, it just wouldn't be in the manifest file so it wouldn't show up twice anymore. Or we can do the other way around if you'd like, but I figure it makes more sense to list this one.

**Comment by rlaphoenix** [comment]
I'm only a helper/maintainer, but I personally think the repo shouldn't be mirrored there in the first place, it just adds confusion on where people should contribute, and is causing a branch of different contributions between the two.

So, I'd have to agree with the removal of the manifest from the community themes repo. What do you think @williamckha ?

**Comment by williamckha** [comment]
Thanks for the heads up @theRealPadster, you can remove the manifest from the community repo. 

Regarding whether this theme should be mirrored in the community repo - this theme was originally added to the community repo before the creation of the spicetify marketplace just to reach the existing users of that collection. I used to manually copy the files from this repo into the community repo, but I've stopped doing that and the version of the theme on the community repo is now outdated. The only reason I've kept it there is because it receives a fairly significant amount of traffic daily on the community repo (more views than this repo in fact). 

Not sure if the spicetify marketplace is now the preferred method of downloading/installing themes, but if so perhaps we should consider removing this theme from the community repo altogether

**Comment by rlaphoenix** [comment]
> I used to manually copy the files from this repo into the community repo, ...

That's not really the best way to do that, if you wanted to mirror it, you should have done pull requests from this repo to the other. That's fair reasons to have the mirror though but spicetify-marketplace is prime to take away the point of the mirror.

It may also be getting the views simply because it's lodged with a bunch of other themes and might have been indexed more because it's indexed with a lot of other themes as well.

**Comment by theRealPadster** [comment]
I don't know if marketplace is the _preferred_ way of getting themes (it's still got a few bugs when adding/removing them that I have yet to get around to fixing), but it does seem to be gaining traction. I'd suggest maybe keeping the listing in the community themes repo, but have it contain a readme that links to this repo. That's what I do with my hide podcasts extension and the community extensions repo. I'll remove from the community manifest though.

**Comment by williamckha** [comment]
> > I used to manually copy the files from this repo into the community repo, ...
> 
> That's not really the best way to do that, if you wanted to mirror it, you should have done pull requests from this repo to the other.

Not really sure how to do this but happy to learn how. Would it involve git submodules?

> It may also be getting the views simply because it's lodged with a bunch of other themes and might have been indexed more because it's indexed with a lot of other themes as well.

I'm a collaborator on the community repo so I can see traffic insights and analytics per theme
