### ISSUE TITLE
Fix repo

### ISSUE THREAD

**Issue by bathtimethiago** [williamckha/spicetify-fluent#58]
I tried to make a PR but it is disabled for some reason...

I made a Repo with some fixes like adsblock, visual bugs and colors
https://github.com/bathtimethiago/spicetify-fluent-fix

**Comment by rlaphoenix** [comment]
Hi, Pull Requests are not disabled. You simply didn't make changes from a fork or clone of this project so it isn't easy to merge your repo into this one.

If you make a fork, then add the changes to the fork, you will then be able to make a pull request for your fork into this project.
I've made an example of how that would look like here: https://github.com/rlaphoenix/spicetify-fluent

As you can see, in my example I have committed your changes to the fork, so you can now see in the commit the diff result, comparing the before/after of your changes.

However, even if you do this we will likely not merge your Pull Request because it has too many changes for various things, with no explanation on why you made the change or what it was to fix.

If you have a change you wish to merge:

1. Fork the project.
2. Make your changes to the project fork, not to a new repo.
3. Make only changes for one thing at a time. I recommend making a new branch called e.g., `adblock-patch`, and `playlist-patch` and make the relevant changes there.
4. You can then make a pull request for merging your fork branch with our master branch.

I will be closing this for now, if you need help just reply here and we will help you out.
